// auth
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";
// user
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const PROFILE_PIC_CHANGE_SUCCESS = "PROFILE_PIC_CHANGE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// scream
export const GET_SCREAM = "GET_SCREAM";
export const GET_SCREAM_SUCCESS = "GET_SCREAM_SUCCESS";
export const GET_INDIVIDUAL_SCREAM = "GET_INDIVIDUAL_SCREAM";
export const GET_INDIVIDUAL_SCREAM_SUCCESS = "GET_INDIVIDUAL_SCREAM_SUCCESS";
export const GET_SCREAM_FAIL = "GET_SCREAM_FAIL";
export const LIKE_SCREAM_SUCCESS = "LIKE_SCREAM_SUCCESS";
export const UNLIKE_SCREAM_SUCCESS = "UNLIKE_SCREAM_SUCCESS";
export const DELETE_SCREAM_SUCCESS = "DELETE_SCREAM_SUCCESS";
export const POST_SCREAM_START = "POST_SCREAM_START";
export const POST_SCREAM_SUCCESS = "POST_SCREAM_SUCCESS";
export const POST_SCREAM_FAIL = "POST_SCREAM_FAIL";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
